# Generated by Django 6.0.1 on 2026-02-23 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsacode',
            name='branch_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.branchlocation'),
        ),
        migrations.AlterField(
            model_name='dsacode',
            name='branch_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.branchstate'),
        ),
    ]
