# Generated by Django 6.0.1 on 2026-02-23 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_dsacode_branch_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banker',
            name='branch_inner_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.branchinnerlocation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banker',
            name='branch_inner_state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.branchinnerstate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banker',
            name='branch_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.branchlocation'),
        ),
        migrations.AlterField(
            model_name='banker',
            name='branch_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.branchstate'),
        ),
    ]
